name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Gather dependencies
        run: go mod download
      - name: Run coverage tests for addition
        run: go test -race -coverprofile=coverage-add.txt -covermode=atomic ./... -run=TestAdd
      - name: Run coverage tests for substraction
        run: go test -race -coverprofile=coverage-substract.txt -covermode=atomic ./... -run=TestSubtract
      - name: Create coverage artifact for debugging
        uses: actions/upload-artifact@v7
        with:
          name: coverage-reports
          path: |
            coverage-add.txt
            coverage-substract.txt
          if-no-files-found: error
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage-add.txt
          disable_search: true
